In [3]:
from selenium import webdriver #webdriver가 사람 대신 크롤러의 역할을 함
from selenium.webdriver.chrome.service import Service #Service는 크롤러에게 로컬 컴퓨터 내 크롬브라우저 드라이브를 일치할 수 있게끔 해주며, 설치를 해 줌
from selenium.webdriver.chrome.options import Options #크롤러가 어떤 환경에서 어떤 방식으로 크롤링 하도록 할지 옵션을 설정
from webdriver_manager.chrome import ChromeDriverManager #실제 드라이브 설치 역할을 함
import time # 특정 사이트 접속 후, 스크립트 기반의 코드를 서버로부터 가져올 때까지 시간을 벌어주는 역할

service = Service(ChromeDriverManager().install()) #실행은 얘가 함
options = Options()

# options.add_argument("--headless") #가상브라우저를 현재 내 로컬컴퓨터에 나타나지 않도록 할 때
# options.add_argument("--disable-gpu") #가상브라우저를 사용하지 않기 때문에 굳이 gpu 메모리를 사용하지 않겠다는 의미
options.add_argument("--disable-dev-shm-usage") #큰 데이터의 크롤링 시, 데이터를 개발자도구 내 임시 메모리 공간을 사용하지 X (로컬의 공간을 바로 사용하겠다)
options.add_argument("--window-size=1920, 1080") #크롤러의 웹 브라우저 사이즈를 세팅
options.add_argument("--start-maximized") #주변 환경요소와 무관하게 브라우저 사이즈를 무조건 크게
options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36") #브라우저 식별 정보 = 우리가 정상적인 웹사이트 방문자임을 알려주는 문장
options.add_argument("--lang=ko_KR") #접속 및 방문하는 브라우저의 기본 세팅 언어
options.add_argument("--no-sandbox") #규제 적용 방지

URL = "https://display.wconcept.co.kr/rn/women"

driver = webdriver.Chrome(service=service, options=options) #()안에 매개변수가 들어가야 함
driver.get(URL)

time.sleep(3)

driver.quit() # 특정 사이트 데이터 수집 후, 가상 브라우저 실행 종료 (*메모리 누수를 방지하기 위함)
print("Wconcept 방문 성공👌")

Wconcept 방문 성공👌

In [6]:
from selenium import webdriver #webdriver가 사람 대신 크롤러의 역할을 함
from selenium.webdriver.common.by import By # 크롤러가 어떤 방식으로 값을 찾아오게 할 것인지 결정
from selenium.webdriver.chrome.service import Service #Service는 크롤러에게 로컬 컴퓨터 내 크롬브라우저 드라이브를 일치할 수 있게끔 해주며, 설치를 해 줌
from selenium.webdriver.chrome.options import Options #크롤러가 어떤 환경에서 어떤 방식으로 크롤링 하도록 할지 옵션을 설정
from webdriver_manager.chrome import ChromeDriverManager #실제 드라이브 설치 역할을 함
import time # 특정 사이트 접속 후, 스크립트 기반의 코드를 서버로부터 가져올 때까지 시간을 벌어주는 역할

service = Service(ChromeDriverManager().install()) #실행은 얘가 함
options = Options()

# options.add_argument("--headless") #가상브라우저를 현재 내 로컬컴퓨터에 나타나지 않도록 할 때
# options.add_argument("--disable-gpu") #가상브라우저를 사용하지 않기 때문에 굳이 gpu 메모리를 사용하지 않겠다는 의미
options.add_argument("--disable-dev-shm-usage") #큰 데이터의 크롤링 시, 데이터를 개발자도구 내 임시 메모리 공간을 사용하지 X (로컬의 공간을 바로 사용하겠다)
options.add_argument("--window-size=1920, 1080") #크롤러의 웹 브라우저 사이즈를 세팅
options.add_argument("--start-maximized") #주변 환경요소와 무관하게 브라우저 사이즈를 무조건 크게
options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36") #브라우저 식별 정보 = 우리가 정상적인 웹사이트 방문자임을 알려주는 문장
options.add_argument("--lang=ko_KR") #접속 및 방문하는 브라우저의 기본 세팅 언어
options.add_argument("--no-sandbox") #규제 적용 방지

URL = "https://display.wconcept.co.kr/rn/women"

driver = webdriver.Chrome(service=service, options=options) #()안에 매개변수가 들어가야 함
driver.get(URL)

time.sleep(3)

# best_button = driver.find_element(By.CSS_SELECTOR, "span.mnbrtm-inner") #찾아올 "클래스.값" 
# -> 단, 클래스는 하나의 문서에서 여러번 쓰일 수 있기 때문에 아래 XPATH로 찾아오는 것이 더 정확해!
best_button = driver.find_element(By.XPATH, "//span[text()='베스트']")
# XPATH 사용시 반드시 클래스명 앞에 // 사용 해야 함. 따옴표 사용도 필수임
best_button.click()
time.sleep(3)


driver.quit() # 특정 사이트 데이터 수집 후, 가상 브라우저 실행 종료 (*메모리 누수를 방지하기 위함)
print("Wconcept 방문 성공👌")

Wconcept 방문 성공👌

In [4]:
dir(driver) # 특정(ex. driver)객체가 사용할 수 있는 매서드를 확인하고 싶을 때 dir(객체명)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__enter__',
 '__eq__',
 '__exit__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_authenticator_id',
 '_bidi_session',
 '_browser',
 '_browsing_context',
 '_check_if_window_handle_is_current',
 '_devtools',
 '_emulation',
 '_fedcm',
 '_file_detector',
 '_get_cdp_details',
 '_input',
 '_is_remote',
 '_mobile',
 '_network',
 '_permissions',
 '_request',
 '_require_fedcm_support',
 '_script',
 '_session',
 '_shadowroot_cls',
 '_start_bidi',
 '_storage',
 '_switch_to',
 '_unwrap_value',
 '_web_element_cls',
 '_webextension',
 '_websocket_connection',
 '_wrap_value',
 'add_cookie',
 'add_credential',
 'add_virtual_authenticator',
 'back',
 'bidi_connection',
 'browser',
 'browsing_context',
 'capabilities',
 'caps',
 'close',
 'command_executor',
 'create_web_element',
 'current_url',
 'current_window_handle',
 'delete_all_cookies',
 'delete_cookie',
 'delete_downloadable_files',
 'delete_network_conditions',
 'dialog',
 'download_file',
 'emulation',
 'error_handler',
 'execute',
 'execute_async_script',
 'execute_cdp_cmd',
 'execute_script',
 'fedcm',
 'fedcm_dialog',
 'file_detector',
 'file_detector_context',
 'find_element',
 'find_elements',
 'fire_session_event',
 'forward',
 'fullscreen_window',
 'get',
 'get_cookie',
 'get_cookies',
 'get_credentials',
 'get_downloadable_files',
 'get_issue_message',
 'get_log',
 'get_network_conditions',
 'get_pinned_scripts',
 'get_screenshot_as_base64',
 'get_screenshot_as_file',
 'get_screenshot_as_png',
 'get_sinks',
 'get_window_position',
 'get_window_rect',
 'get_window_size',
 'implicitly_wait',
 'input',
 'launch_app',
 'locator_converter',
 'log_types',
 'maximize_window',
 'minimize_window',
 'mobile',
 'name',
 'network',
 'options',
 'orientation',
 'page_source',
 'permissions',
 'pin_script',
 'pinned_scripts',
 'print_page',
 'quit',
 'refresh',
 'remove_all_credentials',
 'remove_credential',
 'remove_virtual_authenticator',
 'request',
 'save_screenshot',
 'script',
 'service',
 'session_id',
 'set_network_conditions',
 'set_page_load_timeout',
 'set_permissions',
 'set_script_timeout',
 'set_sink_to_use',
 'set_user_verified',
 'set_window_position',
 'set_window_rect',
 'set_window_size',
 'start_client',
 'start_desktop_mirroring',
 'start_devtools',
 'start_session',
 'start_tab_mirroring',
 'stop_casting',
 'stop_client',
 'storage',
 'supports_fedcm',
 'switch_to',
 'timeouts',
 'title',
 'unpin',
 'virtual_authenticator_id',
 'webextension',
 'window_handles']

In [ ]:
### ----------------------- 아래부터 크롤링 시작 과정이라고 생각하기 ----------------------- ###

In [12]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\user\anaconda3\lib\site-packages (4.46.0)
Requirement already satisfied: certifi>=2026.2.25 in c:\users\user\anaconda3\lib\site-packages (from selenium) (2026.6.17)
Requirement already satisfied: trio<1.0,>=0.31.0 in c:\users\user\anaconda3\lib\site-packages (from selenium) (0.33.0)
Requirement already satisfied: trio-websocket<1.0,>=0.12.2 in c:\users\user\anaconda3\lib\site-packages (from selenium) (0.12.2)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\user\anaconda3\lib\site-packages (from selenium) (4.15.0)
Requirement already satisfied: urllib3<3.0,>=2.6.3 in c:\users\user\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (2.7.0)
Requirement already satisfied: websocket-client<2.0,>=1.8.0 in c:\users\user\anaconda3\lib\site-packages (from selenium) (1.8.0)
Requirement already satisfied: attrs>=23.2.0 in c:\users\user\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (25.4.0)
Requirement already satisfied: sortedcontainers in c:\users\user\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\user\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (3.11)
Requirement already satisfied: outcome in c:\users\user\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0.post0)
Requirement already satisfied: sniffio>=1.3.0 in c:\users\user\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (1.3.0)
Requirement already satisfied: cffi>=1.14 in c:\users\user\anaconda3\lib\site-packages (from trio<1.0,>=0.31.0->selenium) (2.0.0)
Requirement already satisfied: wsproto>=0.14 in c:\users\user\anaconda3\lib\site-packages (from trio-websocket<1.0,>=0.12.2->selenium) (1.3.2)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in c:\users\user\anaconda3\lib\site-packages (from urllib3[socks]<3.0,>=2.6.3->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\user\anaconda3\lib\site-packages (from cffi>=1.14->trio<1.0,>=0.31.0->selenium) (2.23)
Requirement already satisfied: h11<1,>=0.16.0 in c:\users\user\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket<1.0,>=0.12.2->selenium) (0.16.0)

In [13]:
from selenium import webdriver #webdriver가 사람 대신 크롤러의 역할을 함
from selenium.webdriver.common.by import By #크롤러가 어떤 방식으로 값을 찾아오게 할 것인지 결정
from selenium.webdriver.chrome.service import Service #Service는 크롤러에게 로컬 컴퓨터 내 크롬브라우저 드라이브를 일치할 수 있게끔 해주며, 설치를 해 줌
from selenium.webdriver.chrome.options import Options #크롤러가 어떤 환경에서 어떤 방식으로 크롤링 하도록 할지 옵션을 설정
from webdriver_manager.chrome import ChromeDriverManager #실제 드라이브 설치 역할을 함

import pandas as pd #판다스 패키지 사용(판다스를 줄여서 pd라고 부름)
import time #특정 사이트 접속 후, 스크립트 기반의 코드를 서버로부터 가져올 때까지 시간을 벌어주는 역할
import re #regular expression -> 정규표현식 사용시 필요함

service = Service(ChromeDriverManager().install()) #실행은 얘가 함 (내 컴퓨터에 깔려 있는 크롬 브라우저 버전에 딱 맞는 '크롬 드라이버'를 자동으로 찾아서 다운로드하고, 셀레니움과 연결할 준비를 마치는 과정)
options = Options() #브라우저가 켜질 때 어떤 모드와 동작 규칙으로 실행될지 결정하는 '옵션 보관함'을 생성하는 과정

# options.add_argument("--headless") #가상브라우저를 현재 내 로컬컴퓨터에 나타나지 않도록 할 때
# options.add_argument("--disable-gpu") #가상브라우저를 사용하지 않기 때문에 굳이 gpu 메모리를 사용하지 않겠다는 의미
options.add_argument("--disable-dev-shm-usage") #큰 데이터의 크롤링 시, 데이터를 개발자도구 내 임시 메모리 공간을 사용하지 X (로컬의 공간을 바로 사용하겠다)
options.add_argument("--window-size=1920, 1080") #크롤러의 웹 브라우저 사이즈를 세팅
options.add_argument("--start-maximized") #주변 환경요소와 무관하게 브라우저 사이즈를 무조건 크게
options.add_argument("--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36") #브라우저 식별 정보 = 우리가 정상적인 웹사이트 방문자임을 알려주는 문장
options.add_argument("--lang=ko_KR") #접속 및 방문하는 브라우저의 기본 세팅 언어
options.add_argument("--no-sandbox") #규제 적용 방지

URL = "https://display.wconcept.co.kr/rn/women"

driver = webdriver.Chrome(service=service, options=options) #()안에 매개변수가 들어가야 함
driver.get(URL)
time.sleep(3)

# ------------------------------------

# 유틸리티 함수
def to_int(text) :
    num = re.sub(r"[^0-9]","",text) # 대체 매서드 sub() / 가격안에 ,를 빼기 위해서 숫자가 아닌 것들에 대해서는 삭제하고 텍스트로 만들라는 의미
    return int(num) if num else 0

    # 아래 문장을 하나로 나타내면 => 위의 식 return int(num) if num else 0이 되는 것
    # if num : 
    #     return int(num)
    # else :
    #     return 0

# --- 베스트 버튼 클릭 ---
# best_button = driver.find_element(By.CSS_SELECTOR, "span.mnbrtm-inner") #찾아올 "클래스.값" 
# -> 단, 클래스는 하나의 문서에서 여러번 쓰일 수 있기 때문에 아래 XPATH로 찾아오는 것이 더 정확해!
best_button = driver.find_element(By.XPATH, "//span[text()='베스트']")
# XPATH 사용시 반드시 클래스명 앞에 // 사용 해야 함. 따옴표 사용도 필수임
best_button.click()
time.sleep(3)

# --- 상품카드 정보 크롤링 ---
items = driver.find_elements(By.CSS_SELECTOR, "div.product-item.item.type-all")
print(f"✅ 1. 찾은 상품 수: {len(items)}개")


### 상품 수집 데이터 저장용 list 생성 ###
products = list() #혹은 list()대신 [] <- 이렇게 쓰기도 함


# --- 상품별 상세데이터 수집 ---
# 본래 idx는 0부터 찾아오기  때문에, 1부터 찾아오라고 명령 함
for idx, item in enumerate(items, 1) :
    # 상품 랭킹 번호 수집(랭킹은 실시간으로 변동되기 때문에 넘버가 아닌, 랭킹으로 가져와야 함)
    ranking_no = int(item.find_element(By.CSS_SELECTOR, "span.rank").text)

    # 브랜드 이름 수집
    brand_name = item.find_element(By.CSS_SELECTOR, "span.text.title").text.strip()

    # 상품 이름 수집
    product_name = item.find_element(By.CSS_SELECTOR, "span.text.detail").text.strip()
    
    # 판매가격(*소비자가=정가, 할인가, 할인율) 수집
    price_box = item.find_element(By.CSS_SELECTOR, "span.prdc-price")

    # 소비자가(정가)
    try:
        original_price = to_int(price_box.find_element(By.CSS_SELECTOR, "span.customer-price").text)
    except :
        original_price = 0

    # 할인가
    try:
        sale_price = to_int(price_box.find_element(By.CSS_SELECTOR, "span.final-price").text)
    except :
        sale_price = 0
        
    # 할인률
    try:
        discount_rate = to_int(price_box.find_element(By.CSS_SELECTOR, "span.final-discount").text)
    except :
        discount_rate = 0

        

    # --- 평점, 리뷰수, 좋아요수 ---
    try :
        stats = item.find_element(By.CSS_SELECTOR, "span.stats")
    
        # 평점
        try :
            rating = float(stats.find_element(By.CSS_SELECTOR, "span.review em.score").text)
        except :
            rating = 0.0
    
        # 리뷰수
        try :
            review_count = to_int(stats.find_element(By.CSS_SELECTOR, "span.review span.text.cnt").text)
        except :
            review_count = 0
    
        # 좋아요 수
        try :
            like_count = to_int(stats.find_element(By.CSS_SELECTOR, "span.like span.text.cnt").text)
        except :
            like_count = 0
            
    except :
        rating = 0.0
        review_count = 0
        like_count = 0


    # 상품 썸네일 이미지 url
    img_src = item.find_element(By.CSS_SELECTOR, "span.img img").get_attribute("src")
    
    # 상품 상세페이지 url : ex) https://www.wconcept.co.kr/Product/308577412
    img_src = item.find_element(By.CSS_SELECTOR, "span.img img").get_attribute("src")

    match = re.search(r"/(\d{9})[_.]", img_src)
    # print(rank_no, product_name, match.group(1)) #상품 id값 잘 들어오는지 체크하려고 작성한 문장

    if match :
        product_id = match.group(1)
        product_url = f"https://www.wconcept.co.kr/Product/{product_id}"
    else :
        product_id = None
        product_url = ""

    products.append({
        "ranking_no": ranking_no,
        "brand_name": brand_name,
        "product_name": product_name, 
        "original_price": original_price, 
        "sale_price": sale_price, 
        "discount_rate": discount_rate, 
        "rating": rating, 
        "review_count": review_count, 
        "like_count": like_count, 
        "product_id": product_id, 
        "product_url": product_url, 
        "img_src": img_src
    })
    
    # print(ranking_no, brand_name, product_name, original_price, sale_price, discouont_rate, rating, review_count, like_count, img_src, product_url, img_src)

product_df = pd.DataFrame(products)

# driver.quit() # 특정 사이트 데이터 수집 후, 가상 브라우저 실행 종료 명령 (*메모리 누수를 방지하기 위함)
print("✅ 2. Wconcept 상품 기본정보 수집 완료👌")

# 각 상품별 리뷰수집 데이터 저장용 리스트
all_reviews = list() # 또는 []

for product in products[0:1] :
    product_url = product["product_url"]

    # 상품 상세페이지 진입단계
    driver.get(product_url)

    time.sleep(3)

    try : 
        review_button = driver.find_element(By.CSS_SELECTOR, "#reviewCnt1") # id 값이 있었기 때문에 #을 붙임
        review_button.click()
    
        time.sleep(3)
        # print("✅ 2-1. 리뷰버튼 클릭 완료")
    except :
        # print("✅ 2-2. 리뷰버튼이 없는 상품입니다 -> SKIP")
        continue

    print("✅ 3. Wconcept 상품 상세페이지 진입 완료👌")
    for page_no in range(1, 4) :
        if page_no > 1 :
           page_buttons = driver.find_elements(By.CSS_SELECTOR, f"ul#reviewPageNavigation a[title='{page_no}']")

           if len(page_buttons) == 0 :
               print(f"{page_no}페이지가 없습니다.")
               print("리뷰 수집을 종료합니다.")
               
               break
                   
           page_buttons[0].click()
         
           time.sleep(2)
            
            
        rows = driver.find_elements(By.CSS_SELECTOR, "tr")
    
        # 진짜 리뷰 정보값을 가지고 있는 tr만 저장할 목적의 리스트
        review_items = list()
    
        for row in rows :
            review_text_elements = row.find_elements(By.CSS_SELECTOR, "p.pdt_review_text")
    
            if len(review_text_elements) > 0 :
                review_items.append(row)
    
        print(f"{page_no}페이지 리뷰 수: {len(review_items)}개")
        
        for review_index, review in enumerate(review_items, 1) :

            review_no = (page_no - 1) * 6 + review_index
            
            # 리뷰 작성자
            reviewer = review.find_element(By.CSS_SELECTOR, "p.product_review_info_right > em").text.strip()
    
            # 리뷰 작성일
            review_date = review.find_element(By.CSS_SELECTOR, "p.product_review_info_right > span").text.strip()
    
            # 구매 옵션 정보
            try:
                purchase_text = review.find_element(By.CSS_SELECTOR, "div.pdt_review_option span").text.strip()
                purchase_option = re.sub(r"^구매옵션\s*:\s*", "", purchase_text)
                purchase_option = purchase_option.rstrip(",").strip()
    
                if purchase_option.isdigit() :
                    purchase_option = int(purchase_option)
            except :
                purchase_option = ""
                # match = re.search(r"\d+", purchase_text) #group(0), (1)
                # purchase_option = int(match.group(0))
    
            # 리뷰 본문
            review_text = review.find_element(By.CSS_SELECTOR, "p.pdt_review_text").text.strip()
    
            # 리뷰 별점
            star = review.find_element(By.CSS_SELECTOR, "div.star-grade > strong")
            style = star.get_attribute("style")
            match = re.search(r"width:\s*([0-9]+)%", style)
    
            if match :
                star_percent = float(match.group(1))
                review_rating = star_percent / 20
            else :
                review_rating = 0.0
    
            # 리뷰 상세 평가 데이터 저장을 위한 딕셔너리 정의
            evaluations = dict() # 또는 {}
    
            # 리뷰 상세 평가
            try :        
                evaluation_items = review.find_elements(By.CSS_SELECTOR, "ul.product_review_evaluation > li")
                for evaluation in evaluation_items :
                    evaluation_type = evaluation.find_element(By.CSS_SELECTOR, "strong").text.strip()
                    evaluation_value = evaluation.find_element(By.CSS_SELECTOR, "em").text.strip()
                    evaluations[evaluation_type] = evaluation_value
            except :
                continue
    
            # 리뷰 이미지 저장용 리스트
            review_images = list()
    
            # 리뷰 이미지
            images = review.find_elements(By.CSS_SELECTOR, "ul.pdt_review_photo img")
    
            for image in images :
                image_url = image.get_attribute("src")
                review_images.append(image_url)

            review_data = {
                "product_id": product["product_id"],
                "brand_name": product["brand_name"],
                "product_name": product["product_name"],
                "product_url": product["product_url"],
                "review_page": page_no,
                "review_no": review_no,
                "reviewer": reviewer,
                "review_date": review_date,
                "purchase_option": purchase_option,
                "review_text": review_text,
                "review_rating": review_rating,
                "evaluations": evaluations,
                "review_images": review_images
            }

            all_reviews.append(review_data)
                
        #     print(review_no, reviewer, review_date, purchase_option, review_text, review_rating, evaluations, review_images)
        # print(f"✅ 4. 리뷰{page_no}페이지 수집 완료 -> {len(review_items)}개")

print("✅ 4. Wconcept 전체 리뷰 수집 완료")

✅ 1. 찾은 상품 수: 200개

TypeError: expected string or bytes-like object, got 'NoneType'

In [15]:
dir(item)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__firstlineno__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__static_attributes__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_execute',
 '_id',
 '_parent',
 '_upload',
 'accessible_name',
 'aria_role',
 'clear',
 'click',
 'find_element',
 'find_elements',
 'get_attribute',
 'get_dom_attribute',
 'get_property',
 'id',
 'is_displayed',
 'is_enabled',
 'is_selected',
 'location',
 'location_once_scrolled_into_view',
 'parent',
 'rect',
 'screenshot',
 'screenshot_as_base64',
 'screenshot_as_png',
 'send_keys',
 'session_id',
 'shadow_root',
 'size',
 'submit',
 'tag_name',
 'text',
 'value_of_css_property']

In [16]:
from selenium import webdriver # 크롤러 역할
from selenium.webdriver.common.by import By # 크롤러가 어떤 방식으로 값을 찾아오게 할 것인지 결정
from selenium.webdriver.chrome.service import Service # 크롤러에게 로컬컴퓨터 내 크롬브라우저 드라이브 일치 & 설치 지원
from selenium.webdriver.chrome.options import Options # 크롤러가 어떤 환경에서 어떤 방식으로 크롤링 하도록 할지 옵션 설정
from webdriver_manager.chrome import ChromeDriverManager # 실제 드라이브 설치 역할

import pandas as pd
import time # 특정 사이트 접속 후 스크립트 기반의 코드를 서버로부터 가져올 때까지 시간을 벌어주는 역할
import re # regular expression
service = Service(ChromeDriverManager().install())
options = Options()

# options.add_argument("--headless") # 가상브라우저를 현재 내 로컬컴퓨터에 나타나지 않도록 할 때
# options.add_argument("--disable-gpu") # 가상브라우저를 사용하지 않기 때문에 굳이 gpu 메모리를 사용하지 않겠다는 의미
options.add_argument("--disable-dev-shm-usage") # 큰 데이터의 크롤링 시, 데이터를 개발자도구 내 임시메모리 공간을 사용 x (로컬공간) 
options.add_argument("--window-size=1920,1080") # 크롤러의 웹 브라우저 사이즈 세팅
options.add_argument("--start-maximized") # 주변 환경요소와 무관하게 브라우저 사이즈를 무조건 크게
options.add_argument("--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36") # 브라우저 식별 정보 = 우리가 정상적인 웹사이트 방문자
options.add_argument("--lang=ko_KR") # 접속 및 방문하 브라우저의 기본세팅 언어
options.add_argument("--no-sandbox") # 규제 적용 방지

URL = "https://display.wconcept.co.kr/rn/women"

driver = webdriver.Chrome(service=service, options=options)
driver.get(URL)
time.sleep(3)

# 유틸리티 함수
def to_int(text) :
    num = re.sub(r"[^0-9]", "", text)
    return int(num) if num else 0

# 베스트 버튼 클릭
best_button = driver.find_element(By.XPATH, "//span[text()='베스트']")
best_button.click()
time.sleep(3)

# 상품카드 정보 크롤링
items = driver.find_elements(By.CSS_SELECTOR, "div.product-item.item.type-all")
print(f"1. ✅ 찾은 상품 수: {len(items)}개")

# 상품 수집데이터 저장용 리스트 생성
products = list() # []

# 상품별 상세데이터 수집
for idx, item in enumerate(items, 1) :
    # 상품 랭킹 번호 수집
    ranking_no = int(item.find_element(By.CSS_SELECTOR, "span.rank").text)

    # 브랜드 이름 수집
    brand_name = item.find_element(By.CSS_SELECTOR, "span.text.title").text.strip()

    # 상품 이름 수집
    product_name = item.find_element(By.CSS_SELECTOR, "span.text.detail").text.strip()
    
    # 판매가격 (*소비자가, 할인가, 할인률) 수집
    price_box = item.find_element(By.CSS_SELECTOR, "span.prdc-price")

    # 소비자가
    try :
        original_price = to_int(price_box.find_element(By.CSS_SELECTOR, "span.customer-price").text)
    except :
        original_price = 0

    # 할인가
    try :
        sale_price = to_int(price_box.find_element(By.CSS_SELECTOR, "span.final-price").text)
    except :
        sale_price = 0
        
    # 할인률
    try :
        discount_rate = to_int(price_box.find_element(By.CSS_SELECTOR, "span.final-discount").text)
    except :
        discount_rate = 0

    # 평점.리뷰수.좋아요수
    
    stats = item.find_element(By.CSS_SELECTOR, "span.stats")

    # 평점
    try :
        rating = float(stats.find_element(By.CSS_SELECTOR, "span.review em.score").text)
    except :
        rating = 0.0
        
    # 리뷰수
    try :
        review_count = to_int(stats.find_element(By.CSS_SELECTOR, "span.review span.text.cnt").text)
    except :
        review_count = 0
        
    # 좋아요수
    try :
        like_count = to_int(stats.find_element(By.CSS_SELECTOR, "span.like span.text.cnt").text)
    except :
        like_count = 0

    # 상품상세페이지 url
    img_src = item.find_element(By.CSS_SELECTOR, "span.img img").get_attribute("src")

    match = re.search(r"/(\d{9})[_.]", img_src)

    if match :
        product_id = match.group(1)
        product_url = f"https://www.wconcept.co.kr/Product/{product_id}"
    else :
        product_id = None
        product_url = ""

    products.append({
        "ranking_no": ranking_no,
        "brand_name": brand_name,
        "product_name": product_name,
        "original_price": original_price,
        "sale_price": sale_price,
        "discount_rate": discount_rate,
        "rating": rating,
        "review_count": review_count,
        "like_count": like_count,
        "product_id": product_id,
        "product_url": product_url,
        "img_src": img_src
    })
    # https://www.wconcept.co.kr/Product/308577412
    # print(ranking_no, brand_name, product_name, original_price, sale_price, discount_rate, rating, review_count, like_count, product_id, product_url, img_src)
product_df= pd.DataFrame(products)

# driver.quit() # 특정 사이트 데이터 수집 후 가상 브라우저 실행 종료 // 메모리 사용 = 메모리 누수
print("2. ✅ wconcept 상품기본 정보수집 완료!")

# 각 상품별 리뷰수집 데이터 저장용 리스트
all_reviews = list() # []

for product in products[:1] :
    product_url = product["product_url"]

    # 상품 상세페이지 진입단계
    driver.get(product_url)

    time.sleep(3)

    try : 
        review_button = driver.find_element(By.CSS_SELECTOR, "#reviewCnt1")
        review_button.click()
    
        time.sleep(3)
        print("2-1. ✅ 리뷰버튼 클릭 완료!")
    except :
        print("2-2. ✅ 리뷰버튼이 없는 상품입니다 -> SKIP")
        continue

    print("3. ✅ wconcept 상품상세페이지 진입 완료!")
    for page_no in range(1, 4) :
        if page_no > 1 :
            page_buttons = driver.find_elements(By.CSS_SELECTOR, f"ul#reviewPageNavigation a[title='{page_no}']")

            if len(page_buttons) == 0 :
                print(f"{page_no}페이지가 없습니다.")
                print("리뷰 수집을 종료합니다.")

                break

            page_buttons[0].click()

            time.sleep(2)
            
        
        rows = driver.find_elements(By.CSS_SELECTOR, "tr")

        # 진짜 리뷰 정보값을 가지고 있는 tr만 저장할 목적의 리스트
        review_items = list()
    
        for row in rows :
            review_text_elements = row.find_elements(By.CSS_SELECTOR, "p.pdt_review_text")
    
            if len(review_text_elements) > 0 :
                review_items.append(row)

        print(f"{page_no}) 페이지 리뷰 수: {len(review_items)}개")
    
        for review_index, review in enumerate(review_items, 1) :

            review_no = (page_no - 1) * 6 + review_index
            
            # 리뷰 작성자
            reviewer = review.find_element(By.CSS_SELECTOR, "p.product_review_info_right > em").text.strip()
    
            # 리뷰 작성일
            review_date = review.find_element(By.CSS_SELECTOR, "p.product_review_info_right > span").text.strip()
    
            # 구매 옵션정보
            try :
                purchase_text = review.find_element(By.CSS_SELECTOR, "div.pdt_review_option span").text.strip()
                purchase_option = re.sub(r"^구매옵션\s*:\s*", "", purchase_text)
                purchase_option = purchase_option.rstrip(",").strip()
                
                if purchase_option.isdigit() :
                    purchase_option = int(purchase_option)
            except :
                purchase_option = ""
                
                # match = re.search(r"\d+", purchase_text) # group(0), (1)
                # purchase_option = int(match.group(0))
    
            # 리뷰 본문
            review_text = review.find_element(By.CSS_SELECTOR, "p.pdt_review_text").text.strip()
    
            # 리뷰 별점
            star = review.find_element(By.CSS_SELECTOR, "div.star-grade > strong")
            style = star.get_attribute("style")
            match = re.search(r"width:\s*([0-9]+)%", style)
    
            if match :
                star_percent = float(match.group(1))
                review_rating = star_percent / 20
            else :
                review_rating = 0.0
    
            # 리뷰 상세 평가 데이터 저장을 위한 딕셔너리 정의
            evaluations = dict() # | {}
    
            # 리뷰 상세 평가
            try :
                evaluation_items = review.find_elements(By.CSS_SELECTOR, "ul.product_review_evaluation > li")
                for evaluation in evaluation_items :
                    evaluation_type = evaluation.find_element(By.CSS_SELECTOR, "strong").text.strip()
                    evaluation_value = evaluation.find_element(By.CSS_SELECTOR, "em").text.strip()
                    evaluations[evaluation_type] = evaluation_value
            except :
                continue
    
            # 리뷰 이미지 저장용 리스트
            review_images = list()
    
            # 리뷰 이미지
            images = review.find_elements(By.CSS_SELECTOR, "ul.pdt_review_photo img")
        
            for image in images :
                image_url = image.get_attribute("src")
                review_images.append(image_url)

            review_data = {
                "product_id": product["product_id"],
                "brand_name": product["brand_name"],
                "product_name": product["product_name"],
                "product_url": product["product_url"],
                "review_page": page_no,
                "review_no": review_no,
                "reviewer": reviewer,
                "review_date": review_date,
                "purchase_option": purchase_option,
                "review_text": review_text,
                "review_rating": review_rating,
                "evaluations": evaluations,
                "review_images": review_images                
            }

            all_reviews.append(review_data)
            
        #     print(review_no, reviewer, review_date, purchase_option, review_text, review_rating, evaluations, review_images)
        # print(f"4. ✅ 리뷰 {page_no}페이지 수집 완료 -> {len(review_items)}개")
print("4. ✅ wconcept 전체리뷰수집 완료")

1. ✅ 찾은 상품 수: 200개

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"span.stats"}
  (Session info: chrome=152.0.7977.83); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#nosuchelementexception
Stacktrace:
	chromedriver!GetHandleVerifier [0x7ff6cb2ae035+5745]
	chromedriver!(No symbol) [0x7ff6cb1d6a90]
	chromedriver!(No symbol) [0x7ff6cb005d7d]
	chromedriver!(No symbol) [0x7ff6cb0609ea]
	chromedriver!(No symbol) [0x7ff6cb060cfc]
	chromedriver!(No symbol) [0x7ff6cb05475c]
	chromedriver!(No symbol) [0x7ff6cb054606]
	chromedriver!(No symbol) [0x7ff6cb0ae502]
	chromedriver!(No symbol) [0x7ff6cb052e4b]
	chromedriver!(No symbol) [0x7ff6cb053d83]
	chromedriver!GetHandleVerifier [0x7ff6cb6c2f8b+41a69b]
	chromedriver!GetHandleVerifier [0x7ff6cb6f0132+447842]
	chromedriver!GetHandleVerifier [0x7ff6cb6e3e7e+43b58e]
	chromedriver!GetHandleVerifier [0x7ff6cb3a3f5e+fb66e]
	chromedriver!(No symbol) [0x7ff6cb1e419c]
	chromedriver!(No symbol) [0x7ff6cb1dfdd4]
	chromedriver!(No symbol) [0x7ff6cb1dff64]
	chromedriver!(No symbol) [0x7ff6cb1ca91c]
	KERNEL32!BaseThreadInitThunk [0x7ffb252c7374+14]
	ntdll!RtlUserThreadStart [0x7ffb2685cc91+21]

In [ ]:
all_reviews

In [7]:
review_df = pd.DataFrame(all_reviews)
review_df

Empty DataFrame
Columns: []
Index: []

In [ ]:
# 아래 파일이 최종

In [ ]:
# 260911-------------------------------------------------------------------------------------------------------------------

In [ ]:
# 크롤링 코드

In [56]:
from selenium import webdriver # 크롤러 역할
from selenium.webdriver.common.by import By # 크롤러가 어떤 방식으로 값을 찾아오게 할 것인지 결정
from selenium.webdriver.chrome.service import Service # 크롤러에게 로컬컴퓨터 내 크롬브라우저 드라이브 일치 & 설치 지원
from selenium.webdriver.chrome.options import Options # 크롤러가 어떤 환경에서 어떤 방식으로 크롤링 하도록 할지 옵션 설정
from webdriver_manager.chrome import ChromeDriverManager # 실제 드라이브 설치 역할

import pandas as pd
import time # 특정 사이트 접속 후 스크립트 기반의 코드를 서버로부터 가져올 때까지 시간을 벌어주는 역할
import re # regular expression
service = Service(ChromeDriverManager().install())
options = Options()

# options.add_argument("--headless") # 가상브라우저를 현재 내 로컬컴퓨터에 나타나지 않도록 할 때
# options.add_argument("--disable-gpu") # 가상브라우저를 사용하지 않기 때문에 굳이 gpu 메모리를 사용하지 않겠다는 의미
options.add_argument("--disable-dev-shm-usage") # 큰 데이터의 크롤링 시, 데이터를 개발자도구 내 임시메모리 공간을 사용 x (로컬공간) 
options.add_argument("--window-size=1920,1080") # 크롤러의 웹 브라우저 사이즈 세팅
options.add_argument("--start-maximized") # 주변 환경요소와 무관하게 브라우저 사이즈를 무조건 크게
options.add_argument("--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36") # 브라우저 식별 정보 = 우리가 정상적인 웹사이트 방문자
options.add_argument("--lang=ko_KR") # 접속 및 방문하 브라우저의 기본세팅 언어
options.add_argument("--no-sandbox") # 규제 적용 방지

URL = "https://display.wconcept.co.kr/rn/women"

driver = webdriver.Chrome(service=service, options=options)
driver.get(URL)
time.sleep(3)

# 유틸리티 함수
def to_int(text) :
    num = re.sub(r"[^0-9]", "", text)
    return int(num) if num else 0

# 베스트 버튼 클릭
best_button = driver.find_element(By.XPATH, "//span[text()='베스트']")
best_button.click()
time.sleep(3)

# 상품카드 정보 크롤링
items = driver.find_elements(By.CSS_SELECTOR, "div.product-item.item.type-all")
print(f"1. ✅ 찾은 상품 수: {len(items)}개")

# 상품 수집데이터 저장용 리스트 생성
products = list() # []

# 상품별 상세데이터 수집
for idx, item in enumerate(items, 1) :
    # 상품 랭킹 번호 수집
    ranking_no = int(item.find_element(By.CSS_SELECTOR, "span.rank").text)

    # 브랜드 이름 수집
    brand_name = item.find_element(By.CSS_SELECTOR, "span.text.title").text.strip()

    # 상품 이름 수집
    product_name = item.find_element(By.CSS_SELECTOR, "span.text.detail").text.strip()
    
    # 판매가격 (*소비자가, 할인가, 할인률) 수집
    price_box = item.find_element(By.CSS_SELECTOR, "span.prdc-price")

    # 소비자가
    try :
        original_price = to_int(price_box.find_element(By.CSS_SELECTOR, "span.customer-price").text)
    except :
        original_price = 0

    # 할인가
    try :
        sale_price = to_int(price_box.find_element(By.CSS_SELECTOR, "span.final-price").text)
    except :
        sale_price = 0
        
    # 할인률
    try :
        discount_rate = to_int(price_box.find_element(By.CSS_SELECTOR, "span.final-discount").text)
    except :
        discount_rate = 0

    # 평점.리뷰수.좋아요수
    # try :
    #     stats = item.find_element(By.CSS_SELECTOR, "span.stats")
    
    #     # 평점
    #     try :
    #         rating = float(stats.find_element(By.CSS_SELECTOR, "span.review em.score").text)
    #     except :
    #         rating = 0.0
            
    #     # 리뷰수
    #     try :
    #         review_count = to_int(stats.find_element(By.CSS_SELECTOR, "span.review span.text.cnt").text)
    #     except :
    #         review_count = 0
            
    #     # 좋아요수
    #     try :
    #         like_count = to_int(stats.find_element(By.CSS_SELECTOR, "span.like span.text.cnt").text)
    #     except :
    #         like_count = 0
    # except :
    #     continue

    # 평점.리뷰수.좋아요수

    try :
        stats = item.find_element(By.CSS_SELECTOR, "span.stats")
    
        # 평점
        try :
            rating = float(stats.find_element(By.CSS_SELECTOR, "span.review em.score").text)
        except :
            rating = 0.0
    
        # 리뷰수
        try :
            review_count = to_int(stats.find_element(By.CSS_SELECTOR, "span.review span.text.cnt").text)
        except :
            review_count = 0
    
    
        # 좋아요수
        try :
            like_count = to_int(stats.find_element(By.CSS_SELECTOR, "span.like span.text.cnt").text)
        except :
            like_count = 0
    
    except :
        rating = 0.0
        review_count = 0
        like_count = 0

    # 상품상세페이지 url
    img_src = item.find_element(By.CSS_SELECTOR, "span.img img").get_attribute("src")

    match = re.search(r"/(\d{9})[_.]", img_src)

    if match :
        product_id = match.group(1)
        product_url = f"https://www.wconcept.co.kr/Product/{product_id}"
    else :
        product_id = None
        product_url = ""

    products.append({
        "ranking_no": ranking_no,
        "brand_name": brand_name,
        "product_name": product_name,
        "original_price": original_price,
        "sale_price": sale_price,
        "discount_rate": discount_rate,
        "rating": rating,
        "review_count": review_count,
        "like_count": like_count,
        "product_id": product_id,
        "product_url": product_url,
        "img_src": img_src
    })
    # https://www.wconcept.co.kr/Product/308577412
    # print(ranking_no, brand_name, product_name, original_price, sale_price, discount_rate, rating, review_count, like_count, product_id, product_url, img_src)
product_df= pd.DataFrame(products)

# driver.quit() # 특정 사이트 데이터 수집 후 가상 브라우저 실행 종료 // 메모리 사용 = 메모리 누수
print("2. ✅ wconcept 상품기본 정보수집 완료!")

# 각 상품별 리뷰수집 데이터 저장용 리스트
all_reviews = list() # []

for product in products[:3] :
    if product["review_count"] == 0 :
        print("리뷰없음")
        continue

    product_url = product["product_url"]

    # 상품 상세페이지 진입단계
    driver.get(product_url)

    time.sleep(3)

    try : 
        review_button = driver.find_element(By.CSS_SELECTOR, "#reviewCnt1")
        review_button.click()
    
        time.sleep(3)
        # print("2-1. ✅ 리뷰버튼 클릭 완료!")
    except :
        # print("2-2. ✅ 리뷰버튼이 없는 상품입니다 -> SKIP")
        continue

    print("3. ✅ wconcept 상품상세페이지 진입 완료!")
    for page_no in range(1, 4) :
        if page_no > 1 :
            page_buttons = driver.find_elements(By.CSS_SELECTOR, f"ul#reviewPageNavigation a[title='{page_no}']")

            if len(page_buttons) == 0 :
                print(f"{page_no}페이지가 없습니다.")
                print("리뷰 수집을 종료합니다.")

                break

            page_buttons[0].click()

            time.sleep(2)
            
        
        rows = driver.find_elements(By.CSS_SELECTOR, "tr")

        # 진짜 리뷰 정보값을 가지고 있는 tr만 저장할 목적의 리스트
        review_items = list()
    
        for row in rows :
            review_text_elements = row.find_elements(By.CSS_SELECTOR, "p.pdt_review_text")
    
            if len(review_text_elements) > 0 :
                review_items.append(row)

        print(f"{page_no}) 페이지 리뷰 수: {len(review_items)}개")
    
        for review_index, review in enumerate(review_items, 1) :

            review_no = (page_no - 1) * 6 + review_index
            
            # 리뷰 작성자
            reviewer = review.find_element(By.CSS_SELECTOR, "p.product_review_info_right > em").text.strip()
    
            # 리뷰 작성일
            review_date = review.find_element(By.CSS_SELECTOR, "p.product_review_info_right > span").text.strip()
    
            # 구매 옵션정보
            try :
                purchase_text = review.find_element(By.CSS_SELECTOR, "div.pdt_review_option span").text.strip()
                purchase_option = re.sub(r"^구매옵션\s*:\s*", "", purchase_text)
                purchase_option = purchase_option.rstrip(",").strip()
                
                if purchase_option.isdigit() :
                    purchase_option = int(purchase_option)
            except :
                purchase_option = ""
                
                # match = re.search(r"\d+", purchase_text) # group(0), (1)
                # purchase_option = int(match.group(0))
    
            # 리뷰 본문
            review_text = review.find_element(By.CSS_SELECTOR, "p.pdt_review_text").text.strip()
    
            # 리뷰 별점
            star = review.find_element(By.CSS_SELECTOR, "div.star-grade > strong")
            style = star.get_attribute("style")
            match = re.search(r"width:\s*([0-9]+)%", style)
    
            if match :
                star_percent = float(match.group(1))
                review_rating = star_percent / 20
            else :
                review_rating = 0.0
    
            # 리뷰 상세 평가 데이터 저장을 위한 딕셔너리 정의
            evaluations = dict() # | {}
    
            # 리뷰 상세 평가
            try :
                evaluation_items = review.find_elements(By.CSS_SELECTOR, "ul.product_review_evaluation > li")
                for evaluation in evaluation_items :
                    evaluation_type = evaluation.find_element(By.CSS_SELECTOR, "strong").text.strip()
                    evaluation_value = evaluation.find_element(By.CSS_SELECTOR, "em").text.strip()
                    evaluations[evaluation_type] = evaluation_value
            except :
                continue
    
            # 리뷰 이미지 저장용 리스트
            review_images = list()
    
            # 리뷰 이미지
            images = review.find_elements(By.CSS_SELECTOR, "ul.pdt_review_photo img")
        
            for image in images :
                image_url = image.get_attribute("src")
                review_images.append(image_url)

            review_data = {
                "product_id": product["product_id"],
                "brand_name": product["brand_name"],
                "product_name": product["product_name"],
                "product_url": product["product_url"],
                "review_page": page_no,
                "review_no": review_no,
                "reviewer": reviewer,
                "review_date": review_date,
                "purchase_option": purchase_option,
                "review_text": review_text,
                "review_rating": review_rating,
                "evaluations": evaluations,
                "review_images": review_images                
            }

            all_reviews.append(review_data)
            
        #     print(review_no, reviewer, review_date, purchase_option, review_text, review_rating, evaluations, review_images)
        # print(f"4. ✅ 리뷰 {page_no}페이지 수집 완료 -> {len(review_items)}개")
print("4. ✅ wconcept 전체리뷰수집 완료")

1. ✅ 찾은 상품 수: 200개
2. ✅ wconcept 상품기본 정보수집 완료!
리뷰없음
3. ✅ wconcept 상품상세페이지 진입 완료!
1) 페이지 리뷰 수: 6개
2) 페이지 리뷰 수: 6개
3) 페이지 리뷰 수: 6개
3. ✅ wconcept 상품상세페이지 진입 완료!
1) 페이지 리뷰 수: 6개
2) 페이지 리뷰 수: 6개
3) 페이지 리뷰 수: 6개
4. ✅ wconcept 전체리뷰수집 완료

In [57]:
brand_names = product_df["brand_name"].dropna().drop_duplicates().tolist()
print(f"{len(brand_names)}개")

95개

In [ ]:
# 네이버 블로그 API

In [58]:
import re
import requests
import pandas as pd

NAVER_CLIENT_ID = "5db4g311ij"
NAVER_CLIENT_SECRET = "vXbUcbv0h6CSpVSdjTVwrhYBK31SpCQ2zKgE4o9M"

NAVER_BLOG_API_URL = "https://naverapihub.apigw.ntruss.com/search/v1/blog"

headers = {
    "X-NCP-APIGW-API-KEY-ID": NAVER_CLIENT_ID,
    "X-NCP-APIGW-API-KEY": NAVER_CLIENT_SECRET
}

#유틸리티 함수
def clean_text(text) :
    text = re.sub(r"<[^>]+>", "", text)
    text = re.sub(r"&amp;", "", text)
    return text.strip()

brand_names = product_df["brand_name"].dropna().drop_duplicates().tolist()
brand_names = brand_names[:1]


# 블로그 컨텐츠 중 취합할 요소만 찾아서 컨텐츠별 저장할 딕셔너리를 모아놓기위한 용도의 리스트
all_blog_posts = list() # []

for brand_index, brand_name in enumerate(brand_names,  1) :
    params = {
        "query": brand_name,
        "display": 10,
        "start": 1,
        "sort": "date",
        "format": "json"
    }
    try :
        response = requests.get(NAVER_BLOG_API_URL, headers=headers, params=params, timeout = 10)

        if response.status_code == 200 :
            data = response.json()
            items = data.get("items", []) #대체 값으로 []가져와라

            for item in items :
                blog_data = {
                    "search_brand" : brand_name,
                    "title" : clean_text(item.get("title", "")), #대체값으로 ""가져와라
                    "link" : item.get("link", ""), 
                    "description" : clean_text(item.get("description", "")),
                    "bloggername" : item.get("bloggername", ""),
                    "bloggerlink" : item.get("bloggerlink", ""),
                    "postdate" : item.get("postdate", "")
                }
                
                all_blog_posts.append(blog_data)               
                
    except Exception as e :
        print(f"API 호출 중 오류 발생 : {e}") #오류의 구체적인 부분을 알려줌

blog_df = pd.DataFrame(all_blog_posts)

blog_df["postdate"] = pd.to_datetime(blog_df["postdate"], format="%Y%m%d", errors="coerce") #NaT = Not a Time
#만약, 1,000개의 데이터를 수집하고 싶다면? (100개씩 가져와서 총 1000개를 수집하는 반복문)
# for start in range(1, 1000, 100) :
#     params = {
#         "query": brand_name,
#         "display": 10,
#         "start": start,
#         "sort": "date",
#         "format": "json"
#     }

In [60]:
blog_df

,search_brand,title,link,description,bloggername,bloggerlink,postdate
0,팁토이조이,[아기용품] 걸음마 신발 아띠빠스 팁토이조이,https://blog.naver.com/be_happy3_/224406531359,사이즈 안내에 적힌 발사이즈로 맞춰서 주문해보았는데 (+ 더불어 팁토이조이사러 오프...,반짝반짝 빛나는,https://blog.naver.com/be_happy3_,2026-09-09
1,팁토이조이,아기 걷기를 도와주는 팁토이조이 추천,https://blog.naver.com/454y3zo4akge7/224405355720,아기 걷기를 도와주는 팁토이조이 추천 [팁토이조이] 아기 유아 걸음마신발 프리미엄 ...,데일리라이프,https://blog.naver.com/454y3zo4akge7,2026-09-08
2,팁토이조이,아기 걸음마 신발 뉴발란스 뉴비퍼스트 100 핑크 아이보리블루 구....,https://blog.naver.com/hahaohj/224404146313,아마 머지 않아 걸음마를 할 거라는 생각에 들뜨는 마음으로 아기 걸음마 신발을 사줬...,웰컴 우씨네 월드 ෆ˙ᵕ˙ෆ,https://blog.naver.com/hahaohj,2026-09-07
3,팁토이조이,아기 첫 걸음마 신발 추천 팁토이조이 내돈내산 솔직한 후기,https://blog.naver.com/dlcodms8593/224401300517,그렇게 선택했던 신발이 팁토이조이 신발이에요. 아이가 좋아해서 작은 사이즈도 신으려...,띠용이지유,https://blog.naver.com/dlcodms8593,2026-09-04
4,팁토이조이,아기 첫 신발 - 팁토이조이,https://blog.naver.com/kjh6680971/224399797493,팁토이조이 - 걸음마 신발 유후가 손을 잡지 않고 한발 두발 발을... 그러는 와중...,일상의 기록,https://blog.naver.com/kjh6680971,2026-09-03
5,팁토이조이,번쩍배송 팁토이조이 아기 신발 돌 걸음마 후기 참고,https://blog.naver.com/npmsmz4qaovmjk/22439868...,번쩍배송 팁토이조이 아기 신발 돌 걸음마 후기 참고 아기 신발을 찾던 중에 번쩍배송...,하루쭈봉,https://blog.naver.com/npmsmz4qaovmjk,2026-09-02
6,팁토이조이,뉴보시 팁토이조이 걸음마 운동화 돌선물 아기첫 유아신발 추천,https://blog.naver.com/iuzwvhnxbwmox/224397465631,그러다 발견한 게 바로 요 뉴보시 팁토이조이 걸음마 운동화예요.... 뉴보시 팁토이...,식탁 위의 기록,https://blog.naver.com/iuzwvhnxbwmox,2026-09-01
7,팁토이조이,17개월 아기 뉴발란스 IZ530KA 운동화 130 후기!,https://blog.naver.com/alldayon/224395226217,저희 아기는 오니츠카는 130 나이키도 130 팁토이조이는 126 신고 있어요. 사...,오니르니 리빙앤홈,https://blog.naver.com/alldayon,2026-08-30
8,팁토이조이,팁토이조이 펑키F 타피오카 돌 걸음마 신발 사이즈 선택법,https://blog.naver.com/eh92usy3ts3qppslxz6/224...,"팁토이조이 펑키F 타피오카를 살펴보며 가격과 옵션, 사이즈를 고를 때 체크할 기준을...",이히나인님의 블로그,https://blog.naver.com/eh92usy3ts3qppslxz6,2026-08-28
9,팁토이조이,[아기 첫 신발 추천 ]-팁토이조이 126사이즈 내돈내산 후기,https://blog.naver.com/mmon3333/224392450311,오늘은 첫 걸음마 신발로 유명한 팁토이조이 신발 내돈내산 후기... 팁토이조이 걸음...,여노의 일상,https://blog.naver.com/mmon3333,2026-08-27